import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "../styles/globals.css";

// const inter = Inter({ subsets: ["latin"] });              

export const metadata: Metadata = {
  title: "Social media for the soul",
  description: "Generated by spirit",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-100">{children}</body>
    </html>
  );
}
